name: Release Helm Chart to GHCR

on:
  push:
    branches:
      - MBSEmashup-helm
      - main
    # paths:
    #   - 'helm/**'
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.12.0

      - name: Lint Helm Chart
        run: |
          cd helm
          helm lint .

      - name: Package Helm Chart
        run: |
          cd helm
          helm package .

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GHCR
        run: |
          cd helm
          ls *
          echo github.actor ${{ github.actor }}
          echo GITHUB_TOKEN ${{ secrets.GITHUB_TOKEN }}
          echo github.repository_owner ${{ github.repository_owner }}
          helm push sysml-jupyter-*.tgz oci://ghcr.io/${{ github.repository_owner }}/sysml-jupyter